namespace EfSchemaDiff.Core.Models;

public sealed class TableDefinition
{
    public required string Name { get; init; }
    public string? Schema { get; init; }

    /// <summary>Full qualified name schema.table or just table if no schema.</summary>
    public string FullName => Schema is null ? Name : $"{Schema}.{Name}";

    public IReadOnlyList<ColumnDefinition> Columns { get; init; } = [];
    public IReadOnlyList<string> PrimaryKeyColumns { get; init; } = [];
    public IReadOnlyList<ForeignKeyDefinition> ForeignKeys { get; init; } = [];
    public IReadOnlyList<IndexDefinition> Indexes { get; init; } = [];

    /// <summary>Unique constraints (distinct from unique indexes) and alternate keys.</summary>
    public IReadOnlyList<UniqueConstraintDefinition> UniqueConstraints { get; init; } = [];

    /// <summary>True for keyless entity types (HasNoKey()).</summary>
    public bool IsKeyless { get; init; }

    /// <summary>True for SQL view mappings.</summary>
    public bool IsView { get; init; }

    /// <summary>True for temporal tables (HasTemporalTable()).</summary>
    public bool IsTemporal { get; init; }

    /// <summary>True for implicit many-to-many join tables auto-generated by EF Core.</summary>
    public bool IsImplicitJoinTable { get; init; }
}
